### ISSUE TITLE
Add learning resources in README.md section

### ISSUE THREAD

**Issue by codeclassifiers** [codeclassifiers/react30_8_header#2]
Add learning resources in README.md section related to react router.
Any links to youtube tutorials, official docs or articles from Medium, Dev.to or Hashnode are preferred.
Please comment on this issue before opening pull request or contributing to the repository.

**Comment by emma-r-slight** [comment]
I can help with a list of resources.... are you wanting only written articles?

**Comment by Raptor-Dev97** [comment]
I would like to contribute to learning resources.

**Comment by codeclassifiers** [comment]
@emma-r-slight You have been added as a contributor. Feel free to submit your pull request to this repository.

**Comment by codeclassifiers** [comment]
@Raptor-Dev97 and @xdebbie You have been added as a contributor. Feel free to submit your pull request to this repository.

**Comment by codeclassifiers** [comment]
It would be useful if everyone could follow Markdown syntax for submitting changes as mentioned in this [cheatsheet](https://www.markdownguide.org/cheat-sheet/).
