### ISSUE TITLE
Build your own variation of site header

### ISSUE THREAD

**Issue by codeclassifiers** [codeclassifiers/react30_8_header#3]
Modify the CSS or the base code to build your own version of site header.
Submissions by multiple contributors to this issue are allowed.
Steps to contribute:
1. Comment on this issue if you are interested in building your own version
2. Wait for being assigned to the issue and getting solution number
3. Once solution number is assigned, clone the repository and create a folder `solution_[your_assigned_number]` in the repo.
    For example if `solution_3` is assigned to you then you need to create a folder `solution_3` in this repo.
4. If you are a beginner who would only like to modify CSS then copy the code from `solution_1` folder into your assigned folder. If you know react and want to build your own solution then copy the code from `1_starter_code` into your assigned folder.
5. Once finished submit your solution as pull request to this repository. 

Note: No pull request will be accepted until you are added as an assignee to this issue.

**Comment by akaash11** [comment]
I am interested in building my own version of header

**Comment by codeclassifiers** [comment]
@akaash11 You have been added in Assignees list. You can submit your solution in `solution_2` folder.

**Comment by codeclassifiers** [comment]
@VishakhaAwasthi01 You have been added in Assignees list. You can submit your solution in `solution_3` folder.

**Comment by akaash11** [comment]
Hey @codeclassifiers, I have made my PR for solution_2 can you review and accept it with label "hacktoberfest-accepted"

**Comment by emma-r-slight** [comment]
Kia Ora ...I'm going to give this a go as well.

**Comment by codeclassifiers** [comment]
@emma-r-slight Sure. You can submit your variation of site header in `solution_4` folder.

**Comment by codeclassifiers** [comment]
@akaash11 Your submission is successfully merged with relevant labels.
Let me know if there are any issues with official Hacktoberfest contributions.

**Comment by codeclassifiers** [comment]
@emma-r-slight Your submission has been merged with main repo along with relevant labels.
Let me know if it does not get reflected in Hacktoberfest contributions.
